# Generated by Django 4.1 on 2024-04-06 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Data", "0004_data_marked_preprocessed_data_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="data",
            name="task_id",
        ),
    ]
