# Generated by Django 4.1 on 2024-04-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Data", "0005_remove_data_task_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="data",
            name="data_description",
            field=models.CharField(default="", max_length=1000, unique=True),
        ),
    ]
