# Generated by Django 4.1 on 2024-04-07 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Data", "0006_alter_data_data_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="data",
            name="task_type",
            field=models.CharField(default="", max_length=100),
        ),
    ]
