# Generated by Django 4.1 on 2024-04-14 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Data", "0008_ori_data_cols"),
    ]

    operations = [
        migrations.AddField(
            model_name="data",
            name="data_algorithm",
            field=models.CharField(default="", max_length=1000),
        ),
    ]
