# Generated by Django 4.1 on 2024-04-14 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Data", "0009_data_data_algorithm"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="data",
            name="data_algorithm",
        ),
    ]
