# Generated by Django 5.0.3 on 2024-03-23 06:38

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50, unique=True, verbose_name='用户姓名')),
                ('password', models.CharField(blank=True, max_length=50, verbose_name='用户密码')),
                ('phoneNumber', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, unique=True)),
                ('is_admin_or_not', models.BooleanField(verbose_name='是否为管理员')),
            ],
            options={
                'ordering': ['user_id'],
            },
        ),
    ]
