# Generated by Django 4.1 on 2024-03-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0004_alter_user_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_admin_or_not",
            field=models.BooleanField(default=False, verbose_name="是否为管理员"),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.BigAutoField(
                primary_key=True, serialize=False, verbose_name="用户ID"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_name",
            field=models.CharField(
                default="user85d4c49f-3a78-4e82-8657-1f45afc49966",
                max_length=50,
                unique=True,
                verbose_name="用户姓名",
            ),
        ),
    ]
