# Generated by Django 4.1 on 2024-04-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Model", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="model",
            old_name="model_name",
            new_name="algorithm_name",
        ),
        migrations.AlterField(
            model_name="model",
            name="model_description",
            field=models.CharField(max_length=1000),
        ),
    ]
