# Generated by Django 4.1 on 2024-04-07 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Model", "0002_rename_model_name_model_algorithm_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="model",
            name="data_type",
            field=models.CharField(default="", max_length=100),
        ),
    ]
