# Generated by Django 4.1 on 2024-04-06 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Algorithm", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="algorithm",
            name="need_mark",
            field=models.BooleanField(default=False),
        ),
    ]
