# Generated by Django 4.1 on 2024-04-06 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Task", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataManager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_cleaned", models.BooleanField(default=False)),
                ("data_marked", models.BooleanField(default=False)),
                ("data_preprocessed", models.BooleanField(default=False)),
                ("data_generate", models.BooleanField(default=False)),
                (
                    "task_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Task.task"
                    ),
                ),
            ],
        ),
    ]
