# Generated by Django 4.1 on 2024-04-06 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Task", "0002_datamanager"),
    ]

    operations = [
        migrations.RenameField(
            model_name="datamanager",
            old_name="data_cleaned",
            new_name="data_clean",
        ),
        migrations.RenameField(
            model_name="datamanager",
            old_name="data_marked",
            new_name="data_mark",
        ),
        migrations.RenameField(
            model_name="datamanager",
            old_name="data_preprocessed",
            new_name="data_preprocess",
        ),
    ]
