# Generated by Django 4.1 on 2024-04-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Task", "0003_rename_data_cleaned_datamanager_data_clean_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="task_algorithm",
            field=models.CharField(default="", max_length=100),
        ),
    ]
